name: Staticcheck

on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  staticcheck:
    name: Staticcheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Install staticcheck
        run: make install

      - name: Run staticcheck
        run: make lint

      - name: Save results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: staticcheck-results
          path: staticcheck-result.txt
